MOV R3,#12H   // IMMEDIATE ADDRESSING MODE
MOV R3,#00H

MOV	A,#12H	  // REGISTER ADDRESSING MODE
MOV R3,A	  //
MOV R3,#00H

MOV A,#12H	  // DIRECT ADDRESSING MODE
MOV 03H,A	  //
MOV R3,#00H

MOV A,#12H	  // INDIRECT ADDRESSING MODE
MOV R0,#03H	  //
MOV @R0,A	  //
MOV R3,#00H

MOV A,#01H	  // INDEXED ADDRESSING MODE
MOV DPTR,#0000H	  //
MOVC A,@A+DPTR	  //
MOV R3,A		  //

END