// LOADING DATA
MOV PSW,#08H // SWITCHING TO RB 1
MOV R3,#64H
MOV 1BH,#32H
MOV PSW,#18H // TO SHOW CONTENTS OF REGISTERS IN BANK 3 IN KEIL REGISTERS TAB
MOV PSW,#08H // SWITCHING BACK TO RB 1

// SWAPPING
MOV A,R3
MOV R2,A
MOV A,1BH
MOV 1BH,0BH
MOV R3,A
// SWAPPING ENDS HERE

MOV PSW,#18H // TO SHOW CONTENTS OF REGISTERS IN BANK 3 IN KEIL REGISTERS TAB